(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var A3=function(a){a.Z("cardstatechange",a.Fh()&&a.Ik()?1:0)},B3=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},uUa=function(a){var b=g.qn(a);
a=g.un(a);return new g.$m(b.x,b.y,a.width,a.height)},vUa=function(a){return Math.pow(a,3)},wUa=function(a){return 3*a*a-2*a*a*a},E3=function(a){a=g.Ra(a);
delete C3[a];g.qf(C3)&&D3&&D3.stop()},yUa=function(){D3||(D3=new g.K(function(){xUa()},20));
var a=D3;a.isActive()||a.start()},xUa=function(){var a=g.Ua();
g.bf(C3,function(b){zUa(b,a)});
g.qf(C3)||yUa()},F3=function(a,b,c,d){g.Nq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.j=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.C=null},zUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;AUa(a,a.progress);1==a.progress?(a.i=0,E3(a),a.onFinish(),a.ix()):a.Hc()&&a.SC()},AUa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.j.length);for(var c=0;c<a.j.length;c++)a.coords[c]=(a.N[c]-a.j[c])*b+a.j[c]},BUa=function(a,b){g.Se.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.i},G3=function(a,b,c,d,e){F3.call(this,b,c,d,e);
this.element=a},H3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
G3.call(this,a,b,c,d,e)},I3=function(a){g.H.call(this);
this.j=a||window;this.i=[]},J3=function(a){return a.baseUrl||null},K3=function(a,b){return g.Ro(g.En(a,b,void 0),function(c){return!!c})},CUa=function(a,b,c){function d(Y){var ua,Ja,Oa,rb=Y.hovercardButton;
if(!rb)return null;rb=rb.subscribeButtonRenderer;if(!rb)return null;var Db=f(rb.unsubscribedButtonText),lc=f(rb.subscribedButtonText);if(rb.subscribed){var Xa=f(rb.subscriberCountWithUnsubscribeText);var gd=f(rb.subscriberCountText)}else Xa=f(rb.subscriberCountText),gd=f(rb.subscriberCountWithSubscribeText);var sb=null;return Y.signinEndpoint&&(sb=B3(Y,"signinEndpoint","webNavigationEndpointData","url"),sb||(sb=null===(Oa=null===(Ja=null===(ua=rb.signInEndpoint)||void 0===ua?void 0:ua.commandMetadata)||
void 0===Ja?void 0:Ja.webCommandMetadata)||void 0===Oa?void 0:Oa.url),!sb)?null:Db&&(lc||sb)?{subscribed:rb.subscribed,subscribeText:Db,subscribeCount:Xa,unsubscribeText:lc,unsubscribeCount:gd,enabled:rb.enabled,signinUrl:sb,classic:Y.useClassicSubscribeButton}:null}
function e(Y){if(Y){var ua=[],Ja=Y.videoId;Ja&&ua.push("v="+Ja);(Ja=Y.playlistId)&&ua.push("list="+Ja);(Y=Y.startTimeSeconds)&&ua.push("t="+Y);return"/watch?"+ua.join("&")}}
function f(Y){if(!Y)return null;var ua=Y.simpleText;return ua?ua:Y.runs?g.En(Y.runs,function(Ja){return Ja.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,z=null,E=null,I=null,G=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=B3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((E=B3(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(G=f(b.additionalFeesText)),(n=B3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=B3(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:null,ba="";if(b.metadata){var L=f(b.metadata);L&&(ba=L)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ba,callToAction:f(b.callToAction),
ZK:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,iU:n,sessionData:M?{itct:M}:null,XY:p,tv:a?a:null,lU:b.isPlaceholder,impressionUrls:K3(b.impressionUrls||[],J3),aU:K3(b.hovercardShowUrls||[],J3),clickUrls:K3(l.loggingUrls||[],J3),visualElement:g.ex(b.trackingParams),
productPrice:I,additionalFeesText:G}},L3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:K3(a.impressionUrls||[],J3),elements:K3(a.elements||[],function(d,e){return CUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ex(a.trackingParams));return c},M3=function(a){g.qM.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.j=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.N=g.VD(a)||g.ZD(a);this.events=new g.lC(this);g.J(this,this.events);this.events.S(this.player,g.ly("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.my("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.yb);this.events.S(window,"focus",this.WX);this.load();var b=g.Ih("STYLE");(g.qh("HEAD")[0]||document.body).appendChild(b);g.Re(this,function(){g.Mh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},DUa=function(a){return a.player.getVideoData().C?"current":a.N?"new":"current"},N3=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},EUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=L3(f,DUa(a))));O3(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.tq;d&&(c.postParams={ad_tracking:d});if(b=g.Gua(b))if(b=g.vg(b),b=g.rg(b))a.u=g.Ys(b,c)},O3=function(a,b,c){c=void 0===c?!0:c;
a.player.df("creatorendscreen");a.j&&(a.j.dispose(),a.j=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&FUa(a);c=[];d=new g.jy(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().isMobile||(a.j=new g.V({D:"div",K:"ytp-ce-shadow"}),g.cM(a.player,a.j.element,4),a.B=new g.JK(a.j,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=GUa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.cM(a.player,f.element,4);var h=new g.jy(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);HUa(a,
f,e)}else g.qx(new g.hv("buildEndscreenElement null",e))}a.player.Md(c);a.yb()}},FUa=function(a){var b=g.hx(),c=g.ix();
c&&b&&a.endscreen.visualElement&&g.yx(void 0,c,b,[a.endscreen.visualElement])},GUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.L("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ga:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":b.tv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:P3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:Q3(a,b.targetUrl),tabindex:"-1"},U:[{D:"div",Ga:["ytp-ce-video-title"].concat(g.v(c)),V:{dir:g.Sq(b.title||
"")},qa:b.title},{D:"div",K:"ytp-ce-video-duration",qa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.L("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":b.tv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:P3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:Q3(a,
b.targetUrl),tabindex:"-1"},U:[{D:"div",Ga:["ytp-ce-playlist-title"].concat(g.v(c)),V:{dir:g.Sq(b.title||"")},qa:b.title},{D:"div",K:"ytp-ce-playlist-count",U:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":b.tv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],V:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Sq(b.title||"")},qa:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",U:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{D:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:P3(b)}]};c=new g.V(c);var d=g.rh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.T().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.tN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ga:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":b.tv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"div",K:"ytp-ce-website-title",V:{dir:g.Sq(b.title||"")},qa:b.title},{D:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{D:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],V:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:P3(b)},{D:"div",
K:"ytp-ce-expanding-icon",V:IUa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",U:[{D:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.U.push({D:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={D:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":b.tv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"div",K:"ytp-ce-merchandise-title",V:{dir:g.Sq(b.title||"")},qa:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{D:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",V:P3(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",U:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.V(a)}b.lU&&g.N(c.element,"ytp-ce-placeholder");return c},P3=function(a){if(a.ZK)var b=a.ZK.thumbnails;
return IUa(b?b[b.length-1].url:null)},IUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},HUa=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.N(b.element,"ytp-ce-force-expand"),R3(a,c.id,!0)):(g.Eq(b.element,"ytp-ce-force-expand"),g.Eq(b.element,"ytp-ce-element-hover"),R3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Pa("mouseenter",function(){S3(a,b,c)});
b.Pa("mouseleave",function(){T3(a,b,c)});
a.player.T().isMobile||b.Pa("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){JUa(a,c,m)});
b.Pa("keypress",function(m){JUa(a,c,m)});
b.Pa("focus",function(){S3(a,b,c)});
b.Pa("blur",function(){T3(a,b,c)});
b.Pa("touchstart",function(){S3(a,b,c)});
var l=g.th("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Eq(b.element,"ytp-ce-element-hover");g.Eq(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.th("ytp-sb-subscribe",b.element));d(g.th("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",h)},JUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Cq(d,"ytp-ce-element");){g.Cq(d,"subscribe-label")&&U3(a,b);
if(g.Cq(d,"ytp-ce-channel-subscribe"))return;d=g.Nh(d)}if(!d||g.Cq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])T3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.XY)U3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.vg(Q3(a,b.targetUrl)),c=g.rg(c),g.iL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().C,f=function(){var h=Q3(a,b.targetUrl),l=b.sessionData,m=g.Js(h);e&&m&&(m.v||m.list)?a.player.ek(m.v,l,m.list,!1):
g.hL(h,l)};
U3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Q3=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.wE(a)+b}else return"";return b},S3=function(a,b,c){g.Cq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.T().isMobile?(new g.K(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),V3(a,c.aU),R3(a,c.id,!0))},T3=function(a,b,c){g.Eq(b.element,"ytp-ce-element-hover");
g.Eq(b.element,"ytp-ce-force-expand");R3(a,c.id,!1)},R3=function(a,b,c){a.j&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},V3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||N3(a))c&&c();else{b=KUa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.lw(b[a],d)}},U3=function(a,b,c){V3(a,b.clickUrls,c);
(a=g.ix())&&b.iU&&g.Ex(a,b.visualElement)},KUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(LUa(b[d],c));return a},LUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},MUa=function(a){return"string"===typeof a?a:""},W3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},NUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},X3=function(a){return a.value?a.value:null},Y3=function(a){if(!a)return null;
var b=g.vg(MUa(a.value));b=g.rg(b);if(!b)return null;var c=W3(a.target,OUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new NUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},PUa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},SUa=function(a){if(!a)return null;
var b=W3(a.type,QUa),c=W3(a.trigger,RUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Y3(a?a:null);return b?new PUa(b,c,a):null},TUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},VUa=function(a){return(a=UUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},UUa=function(a,b){return g.Xb(a.action,b,void 0)},WUa=function(a,b){this.context=a;
this.i=b},$3=function(a){return a.customMessage?Z3("div","iv-card-message",a.customMessage):""},a4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",V:{style:a},U:c}},b4=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Z3("li","",c.value));return{D:"ul",K:"iv-card-meta-info",U:b}},Z3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Sq(c);return{D:a,V:b,qa:c}},XUa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Uy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Uy+");");c.dir=g.Sq(a.customMessage);var d=[{D:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ga:b,V:c,U:d}},c4=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},YUa=function(a,b){this.merchant=a;
this.price=b},ZUa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},$Ua=function(a,b){return b?b:ZUa(a)?"current":"new"},d4=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.fb=!1;this.Qa=new Map;this.Ta=new Map;this.context.G.addEventListener(g.ly("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.my("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)})},e4=function(a,b,c,d,e,f,h){a.context.i.Pa(b,"click",function(l){a.TC(c,d,e,f||[],h||0,l)});
a.context.i.Pa(b,"touchstart",function(){a.fb=!1});
a.context.i.Pa(b,"touchmove",function(){a.fb=!0})},aVa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},f4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
gP:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
MB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},i4=function(a,b,c){d4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ia=this.wb=this.u=this.isInitialized=!1;this.va=null;this.cards=[];this.jb=this.N=this.Ha=this.C=this.La=this.i=null;this.Y=[];this.J=this.Ke=this.ya=null;this.I=0;this.xa=new g.K(g.Ka,c.X.xe?4E3:3E3);g.J(this,this.xa);this.Ya=new g.K(g.Ka);g.J(this,this.Ya);this.ea=new WUa(c,function(e,f,h,l,m,n){e4(d,e,f,h,l,m,n)});
this.W=new g.V({D:"div",K:"iv-drawer",V:{id:"iv-drawer"},U:[{D:"div",K:"iv-drawer-header",V:{"aria-role":"heading"},U:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ga:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.J(this,this.W);this.B=this.W.element;this.Wa=new g.JK(this.W,330);g.J(this,this.Wa);this.kb=g.th("iv-drawer-header-text",this.B);this.j=g.th("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.wb&&g4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wb=d.u)&&h4(d)})},bVa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){g4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){h4(a)});
var c=b.headerText;g.Ph(a.kb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.ya=g.ex(b.trackingParams);a.J=g.ex(b.closeTrackingParams);a.Ke=g.ex(b.iconTrackingParams)},cVa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.command),Tl:d.trackingParams?g.ex(d.trackingParams):null,gj:e.trackingParams?
g.ex(e.trackingParams):null,Ke:f&&f.trackingParams?g.ex(f.trackingParams):null,imageUrl:k4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.qy(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Uy:null,title:d.title?g.qy(d.title):"",customMessage:d.callToAction?g.qy(d.callToAction):"",url:d.command.urlEndpoint.url?Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};l4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.endpoint),Tl:d.trackingParams?g.ex(d.trackingParams):null,gj:e.trackingParams?g.ex(e.trackingParams):null,Ke:f&&f.trackingParams?
g.ex(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.qy(d.customText):null,profileImageUrl:k4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.qy(d.channelName):"",metaInfo:[d.subscriberCountText?g.qy(d.subscriberCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
l4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.action),Tl:d.trackingParams?g.ex(d.trackingParams):
null,gj:e.trackingParams?g.ex(e.trackingParams):null,Ke:f&&f.trackingParams?g.ex(f.trackingParams):null,ey:k4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.qy(d.customMessage):null,playlistVideoCount:g.qy(d.playlistVideoCount),title:d.playlistTitle?g.qy(d.playlistTitle):"",metaInfo:[d.channelName?g.qy(d.channelName):"",d.videoCountText?g.qy(d.videoCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:aVa(d.action)})};l4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.action),Tl:d.trackingParams?g.ex(d.trackingParams):null,gj:e.trackingParams?g.ex(e.trackingParams):null,Ke:f&&f.trackingParams?g.ex(f.trackingParams):
null,ey:k4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.qy(d.lengthString):null,customMessage:d.customMessage?g.qy(d.customMessage):null,title:d.videoTitle?g.qy(d.videoTitle):"",metaInfo:[d.channelName?g.qy(d.channelName):"",d.viewCountText?g.qy(d.viewCountText):""],isLiveNow:!!d.badge,url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:aVa(d.action)})};l4(a,b)}a.I++},k4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},j4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},eVa=function(a,b){if(b=dVa(a,b))b===a.i&&(a.i=null),a.G.removeCueRange(b.card.id),g.Mh(b.RD),g.fc(a.cards,b),a.Xy(),m4(a)},g4=function(a,b,c){if(!a.u){a.Wa.show();
a.La=new g.K(function(){g.N(a.context.G.getRootNode(),g.fT.IV_DRAWER_OPEN)},0);
a.La.start();a.va=g.Nt(a.j,"mousewheel",function(h){a.xa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.j.scrollTop+=h});
a.u=!0;var d=g.ix();d&&a.ya&&a.J&&g.Cx(d,[a.ya,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.IM||(f.IM=!0,fVa(a.context.logger,f.card.tracking.impression,b)),d&&g.Cx(d,[f.card.Tl]);A3(a.G);c&&(a.C=new g.K(function(){a.Ha=a.N;a.jb.focus()},330),a.C.start())}},h4=function(a){a.u&&(a.Wa.hide(),g.Ot(a.va),a.va=null,g.Eq(a.context.G.getRootNode(),g.fT.IV_DRAWER_OPEN),a.u=!1,A3(a.G),a.C&&a.C.stop(),a.C=new g.K(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),a.C.start())},
hVa=function(a){g.Dq(a.element,[g.fT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.cM(a.G,a.B,5);gVa(a);a.N=g.th("ytp-cards-button",a.G.getRootNode());a.jb=g.th("iv-drawer-close-button",a.B);a.isInitialized=!0},gVa=function(a){var b=g.th("iv-drawer-close-button",a.B);
a.context.i.Pa(b,"click",a.AS,a);a.context.i.Pa(a.j,"touchend",function(){a.xa.start()});
a.context.i.Pa(a.j,"scroll",a.NS,a);a.context.j.subscribe("onHideControls",function(){a.Ia=!0});
a.context.j.subscribe("onShowControls",function(){a.Ia=!1});
a.context.j.subscribe("onVideoAreaChange",function(){a.Ia=g.Cq(a.G.getRootNode(),"ytp-autohide")});
a.Y.push(g.gu("iv-button-shown",a.rU,a));a.Y.push(g.gu("iv-button-hidden",a.qU,a));a.Y.push(g.gu("iv-teaser-shown",a.fR,a));a.Y.push(g.gu("iv-teaser-hidden",a.sU,a));a.Y.push(g.gu("iv-teaser-clicked",a.eR,a))},l4=function(a,b){a.isInitialized||hVa(a);
eVa(a,b.id);var c=iVa(a,b);if(c){var d={card:b,RD:c.element,IM:!1},e=jVa(a,d);g.nc(a.cards,e,0,d);c.Ca(a.j,e);a.Xy();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,m4(a),kVa(a,d),g4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&lVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){lVa(a,d)}),m4(a))}},iVa=function(a,b){switch(b.type){case "simple":a=a.ea;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var d=XUa(b);c={D:"div",Ga:["iv-card"],U:[{D:"a",K:"iv-click-target",V:{href:b.url?X3(b.url)||"":""},U:[a4(b.imageUrl,c),{D:"div",K:"iv-card-content",U:[Z3("h2",void 0,b.title),d]}]}]};c=new g.V(c);c4(a,g.sh("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ea,c={D:"div",Ga:["iv-card","iv-card-channel"],U:[{D:"a",Ga:["iv-click-target"],V:{href:X3(b.url)||"","data-ytid":b.channelId},U:[a4(b.profileImageUrl),
{D:"div",K:"iv-card-content",U:[$3(b),{D:"h2",K:"iv-card-primary-link",qa:b.title},b4(b)]}]}]},c=new g.V(c),c4(a,g.sh("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ea,c={D:"div",Ga:["iv-card","iv-card-playlist"],U:[{D:"a",K:"iv-click-target",V:{href:X3(b.url)||""},U:[a4(b.ey,{D:"div",K:"iv-card-image-overlay",U:[{D:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",U:[$3(b),Z3("h2","iv-card-primary-link",b.title),b4(b)]}]}]},c=new g.V(c),
c4(a,g.sh("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ea;var e=!g.cc(b.offers);c=["iv-card"];d="";var f=XUa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",qa:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",qa:f.merchant}),f={D:"div",U:e});e=b.url?X3(b.url)||"":"";c={D:"div",Ga:c,V:{tabindex:"0"},U:[{D:"a",Ga:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",U:[b.sponsored?{D:"div",K:"iv-card-sponsored",U:["Sponsored",{D:"div",K:"iv-ad-info-container",U:[{D:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",U:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",V:{href:e},U:[Z3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Ih("span");g.Ph(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.yd(d,"adInfo");c4(a,g.sh("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ea,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ga:["yt-badge","yt-badge-live"],qa:"LIVE NOW"}:null,e={D:"div",Ga:["iv-card","iv-card-video"],U:[{D:"a",K:"iv-click-target",V:{href:(null===(c=b.url)||void 0===c?void 0:X3(c))||""},U:[a4(b.ey,d),{D:"div",K:"iv-card-content",U:[$3(b),Z3("h2","iv-card-primary-link",b.title),b4(b),f]}]}]},c=new g.V(e),
c4(a,g.sh("iv-click-target",c.element),b,b.url),c;default:return null}},jVa=function(a,b){if(0===a.cards.length)return 0;
a=g.Yb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},mVa=function(a){return a.i?"productListing"===a.i.card.type:g.Fn(a.cards,function(b){return"productListing"===b.card.type})},m4=function(a){g.O(a.G.getRootNode(),"ytp-cards-shopping-active",mVa(a))},lVa=function(a,b){if(!g.Cq(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.ix(),d=a.i?a.i.card.Ke:a.Ke;
c&&d&&g.Dx(c,[d]);a.i=b;m4(a)}if(c="none"!=a.element.style.display)c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d;c&&b.card.teaserDurationMs&&a.G.Ut(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ya.isActive()||((!a.u||!a.xa.isActive()&&a.Ia)&&kVa(a,b),a.Ya.start(910+b.card.teaserDurationMs))}},kVa=function(a,b){a.W.sb?(b=new F3([0,
a.j.scrollTop],[0,b.RD.offsetTop],600,wUa),a.context.u.Pa(b,"animate",function(c){a.j.scrollTop=c.y}),a.context.u.Pa(b,"finish",function(c){a.j.scrollTop=c.y}),b.play()):(g.UJ(a.W,!0),a.j.scrollTop=b.RD.offsetTop,g.UJ(a.W,!1))},n4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},dVa=function(a,b){return g.Xb(a.cards,function(c){return c.card.id===b})},o4=function(a,b,c){d4.call(this,a,b);
this.annotation=c;this.isActive=!1},nVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},p4=function(a,b,c){o4.call(this,a,b,c);
this.j=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},oVa=function(a,b){var c=void 0===c?0:c;
var d=uUa(b).width;g.on(b,d);c=new H3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,vUa);g.J(a,c);a.context.u.Pa(c,"begin",function(){g.vn(b,!0)});
c.play()},rVa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({D:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.tN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.i.Ca(d));var f=a.createElement({D:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.vn(h,!1);var l=a.createElement({D:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.gn(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.K(function(){pVa(a,h,l)},500);
g.J(a,a.u);a.context.i.Pa(a.element,"mouseover",function(){qVa(a,h,l,f,b.image_height)});
a.context.i.Pa(a.element,"mouseout",function(){a.u.start()})}},qVa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.un(b);a.i||(b.style.width=g.nn(f.width,!0),c.style.width=g.nn(f.width,!0));g.gn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.gn(d,"right","1px");a.B=!0;g.vn(b,!0);a.C=new g.K(function(){g.N(this.element,"iv-branding-active")},0,a);
a.C.start()}},pVa=function(a,b,c){g.Eq(a.element,"iv-branding-active");
a.I=new g.K(function(){g.vn(b,!1);a.i||(c.style.width=g.nn(0,!0))},250);
a.I.start();a.B=!1},sVa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.X=c;this.videoData=d;this.logger=e;this.G=f;this.j=h},q4=function(a,b,c){o4.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.W=!1;this.I=5E3;this.j=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ga:["iv-promo-contents"]});this.C=new g.K(function(){d.i.setAttribute("aria-hidden","true");g.vn(d.u,!1);g.vn(d.j,!0)},700,this);
g.J(this,this.C)},tVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=VUa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",V:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&e4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.Og(f,X3(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",U:[{D:"strong",
qa:b.text_line_1}]});var m=a.createElement({D:"p",U:[{D:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ga:["iv-button","iv-promo-button"],U:[{D:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&e4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.i,
"iv-click-target");e&&e4(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",U:[{D:"span",qa:b.text_line_1}]}),m=a.createElement({D:"p",U:[{D:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"LIVE NOW"})),g.N(a.i,"iv-click-target"),e&&e4(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.j=a.createElement({D:"button",Ga:["iv-promo-expand","ytp-button"]});a.j.title="Expand";a.context.i.Pa(a.j,"click",function(r){r4(a,5E3,r)});
c.appendChild(a.j);g.vn(a.j,!1);a.context.i.Pa(a.element,"mouseover",a.CT,a);a.context.i.Pa(a.element,"mouseout",a.BT,a);a.context.i.Pa(a.element,"touchend",function(r){r4(a,5E3,r)});
a.u=a.createElement({D:"button",Ga:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.Pa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.xT:a.wT,a);c.appendChild(a.u);g.Dq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},r4=function(a,b,c){c.stopPropagation();
uVa(a);vVa(a,b);a.i.focus()},wVa=function(a){a.isCollapsed||a.N||a.B||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},uVa=function(a){a.C.stop();
a.isCollapsed&&(g.Fq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.vn(a.j,!1),g.vn(a.u,!0))},vVa=function(a,b){a.B||(a.B=g.zi(function(){s4(this);
wVa(this)},b,a))},s4=function(a){a.B&&(g.C.clearTimeout(a.B),a.B=null)},xVa=function(a){this.G=a},fVa=function(a,b,c){b&&(c?t4(a,b.map(function(d){return g.hq(d,c)})):t4(a,b))},t4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.lw(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},u4=function(a){g.qM.call(this,a);
var b=this;this.N=!1;this.loadNumber=0;this.I={};this.logger=new xVa(this.player);this.B=new g.lC(this);this.C=this.Cl=null;this.events=new g.lC(this);this.J=this.i=null;this.W=[];g.J(this,this.B);this.B.S(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.B.S(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.B.S(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.B.S(this.player,"resize",function(d){b.Z("resize",d)});
this.B.S(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.gR,this);this.subscribe("resize",this.QA,this);this.player.T().W.subscribe("vast_info_card_add",this.XN,this);g.J(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.j=new g.V({D:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.j);g.cM(this.player,this.j.element,4);this.j.hide();this.u=new g.V({D:"div",Ga:["ytp-iv-video-content"]});g.J(this,this.u);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.u.element.appendChild(a);this.Uq()&&this.load();var c=this.createElement({D:"style"});(g.qh("HEAD")[0]||document.body).appendChild(c);g.Re(this,function(){g.Mh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},yVa=function(a){a=a.createElement({D:"div",
Ga:["annotation","annotation-type-custom"]});g.vn(a,!1);return a},zVa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.UJ(a.j,b);g.UJ(a.u,b)},AVa=function(a,b,c){a.N=!0;
a.C=g.Ys(b,c)},BVa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(BVa(a,e))}return c},EVa=function(a){var b=a.player.getVideoData();
if(b.Qa){var c=a.player.T().W.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Rs(h)&&h.responseXML?h.responseXML:null)&&v4(a,h)}};
g.ot()&&(d.onFinish=CVa(a,d.onFinish));d.postParams={ic_only:"1"};DVa(d,c);a.N=!0;g.Ys(b.Qa,d)}}},DVa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Cv&&(a.postParams.ic_coll=b.Cv);b.ez&&(a.postParams.ic_xml=b.ez);b.jy&&(a.postParams.ic_track=b.jy)},FVa=function(a){var b=new g.V({D:"div"});
g.vn(b.element,!1);var c=new i4(a.player,b.element,w4(a));g.J(c,b);b.Ca(a.j.element);c.Nx();return c},w4=function(a){if(!a.J){var b=new I3(a);
g.J(a,b);var c=new g.Jl(a);g.J(a,c);a.J=new sVa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Ld)}return a.J},v4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ix();if(e){var f=g.hx();f&&g.yx(void 0,e,f,[g.ex(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=BVa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=W3(f.type,GVa),p=W3(f.style,HVa),r=MUa(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=SUa;if(null==u)var x=null;else if(g.Na(u)){l=[];for(var y=g.q(u),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var I=f(u);x=I?[I]:[]}e=m&&n?new TUa(m,n,p,x,t):null}else e=null}catch(ua){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=yVa(f),M=null;switch(l.type){case "branding":if(f.player.T().Qb)break;f.j.element.appendChild(G);M=new p4(G,w4(f),l);break;case "promotion":g.cM(f.player,G,4),M=new q4(G,w4(f),l)}M&&M.Nx();if(f=M)g.J(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=FVa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var ba=e&&e.data&&e.data.card_type;
f=e.data;if(ba)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,gP:l.teaser_impression,MB:l.teaser_click},G=f.tracking_params||{},M=null,ba){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.ex(G.card):null,gj:G.teaser?g.ex(G.teaser):null,Ke:G.icon?g.ex(G.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.ex(G.card):
null,gj:G.teaser?g.ex(G.teaser):null,Ke:G.icon?g.ex(G.icon):null,ey:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "productListing":f.signin_url&&(M=Y3({target:"current",value:f.signin_url}));ba=[];for(var L=f.offers||[],Y=0;Y<L.length;Y++)ba.push(new YUa(g.gh(L[Y].merchant),g.gh(L[Y].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.ex(G.card):null,gj:G.teaser?g.ex(G.teaser):null,Ke:G.icon?g.ex(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Uy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Qfa:M,Pfa:f.signin_title?f.signin_title:void 0,Ofa:f.signin_message?f.signin_message:void 0,offers:ba};l4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.ex(G.card):null,gj:G.teaser?g.ex(G.teaser):
null,Ke:G.icon?g.ex(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Uy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.ex(G.card):null,gj:G.teaser?g.ex(G.teaser):null,Ke:G.icon?g.ex(G.icon):null,ey:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},l4(c,e)}}else bVa(a.i,e);c=!0}}c&&(A3(a.player),a.QA())},IVa=function(a,b){var c=!1;
a.i||(a.i=FVa(a),g.J(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(cVa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.qy(b.headerText):"",g.Ph(c.kb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ya=b.trackingParams?g.ex(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.ex(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ke=b.icon.infoCardIconRenderer.trackingParams?
g.ex(b.icon.infoCardIconRenderer.trackingParams):null,A3(a.player),a.QA())},JVa=function(a,b,c,d,e){if(!a.player.T().Qb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new PUa("openUrl","click",new NUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.qy(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.qy(b.subscriberCountText))):(b.subscriberCountText&&(e=g.qy(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.qy(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.qy(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.qy(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new TUa(c,"branding","branding",f,d);l=yVa(a);a.j.element.appendChild(l);f=new p4(l,w4(a),f);f.Nx();g.J(f,f);a.I[c]=f}},CVa=function(a,b){return function(){var c=g.Ba.apply(0,arguments);
a.isDisposed()||a.W.push(g.au.Tf(function(){b.apply(null,g.v(c))}))}},KVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.WL.prototype.Ut=g.da(18,function(a,b){var c=g.FM(this.tb());c&&c.Ut(a,b)});
var C3={},D3=null;g.Va(F3,g.Nq);g.k=F3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.j;else if(this.Hc())return!1;E3(this);this.startTime=a=g.Ua();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.MA();this.xi("play");-1==this.i&&this.xi("resume");this.i=1;var b=g.Ra(this);b in C3||(C3[b]=this);yUa();zUa(this,a);return!0};
g.k.stop=function(a){E3(this);this.i=0;a&&(this.progress=1);AUa(this,this.progress);this.xi("stop");this.ix()};
g.k.pause=function(){this.Hc()&&(E3(this),this.i=-1,this.xi("pause"))};
g.k.ra=function(){0==this.i||this.stop(!1);this.xi("destroy");F3.re.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.SC=function(){this.xi("animate")};
g.k.xi=function(a){this.dispatchEvent(new BUa(a,this))};
g.Va(BUa,g.Se);g.Va(G3,F3);G3.prototype.B=g.Ka;G3.prototype.SC=function(){this.B();G3.re.SC.call(this)};
G3.prototype.ix=function(){this.B();G3.re.ix.call(this)};
G3.prototype.MA=function(){this.B();G3.re.MA.call(this)};
g.Va(H3,G3);H3.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(I3,g.H);I3.prototype.Pa=function(a,b,c,d){c=(0,g.Sa)(c,d||this.j);a=g.Nt(a,b,c);this.i.push(a);return a};
I3.prototype.wA=function(a,b,c,d){c=(0,g.Sa)(c,d||this.j);a=g.Qka(a,b,c);this.i.push(a);return a};
I3.prototype.wc=function(a){g.Ot(a);g.fc(this.i,a)};
I3.prototype.ra=function(){g.Ot(this.i);this.i.length=0;g.H.prototype.ra.call(this)};g.w(M3,g.qM);g.k=M3.prototype;g.k.load=function(){g.qM.prototype.load.call(this);if(!N3(this)){var a=g.Hua(this.player.getVideoData());a?(a=L3(a,DUa(this)),O3(this,a,!1)):EUa(this)}};
g.k.unload=function(){O3(this,null);this.u&&(this.u.abort(),this.u=null);g.qM.prototype.unload.call(this)};
g.k.sf=function(a,b){return N3(this)?"loadCustomEndscreenRenderer"===a?(a=L3(b,"new"),O3(this,a),!0):null:null};
g.k.getOptions=function(){return N3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<LVa.length;f++){var h=Math.abs(b.width-LVa[f]);if(-1===e||d>=h)e=f,d=h}d=MVa[e];this.j&&g.gn(this.j.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.tn(e.element,Math.round(h.width*a.width),f);g.on(e.element,m,n);g.Fq(e.element,NVa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Fq(e.element,MVa);g.N(e.element,d);(e=g.rh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.gn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())V3(this,this.endscreen.impressionUrls),(a=g.ix())&&this.endscreen.visualElement&&g.zx(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");V3(this,c.impressionUrls);(b=g.ix())&&g.zx(b,c.visualElement,void 0);this.player.T().u&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Eq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Eq(b,"ytp-ce-shown");this.player.T().u&&this.player.Oa("endscreenelementhidden",a)}};
g.k.WX=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Fq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var LVa=[346,426,470,506,570,640,853,1280,1920],MVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),NVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var OUa={R3:"current",g$:"new"};var QUa={CLOSE:"close",z$:"openUrl",SUBSCRIBE:"subscribe"},RUa={u0:"click",CLOSE:"close",m5:"hidden",cba:"rollOut",dba:"rollOver",Yba:"shown"};var HVa={r_:"anchored",VP:"branding",CHANNEL:"channel",Q3:"cta",p5:"highlightText",Q6:"label",PLAYLIST:"playlist",uaa:"popup",hca:"speech",SUBSCRIBE:"subscribe",zca:"title",VIDEO:"video",dea:"website"},GVa={VP:"branding",e0:"card",i4:"drawer",o5:"highlight",u8:"marker",Eaa:"promotion",TEXT:"text",Hea:"widget"};g.w(d4,g.H);g.k=d4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.jy(a,b,{id:c,namespace:"annotations_module"});d&&this.Qa.set(a,d);e&&this.Ta.set(a,e);this.context.G.Md([a])};
g.k.Nx=function(){this.context.j.subscribe("resize",this.Xy,this)};
g.k.TC=function(a,b,c,d,e,f){if(this.fb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Mh(this.element)};
g.k.Xy=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=X3(a);if(f){var h=$Ua(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Js(f||"");m&&n&&(n.v||n.list)?e.context.G.ek(n.v,b,n.list,!1):g.iL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);t4(this.context.logger,c,l,d);ZUa(f)||(c=g.ix(),d=b.itct,c&&d&&g.Ex(c,g.ex(d)))}};
g.k.ra=function(){this.Qa.clear();this.Ta.clear();g.H.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.w(i4,d4);g.k=i4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.un(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Xy=function(){var a=this.isAvailable();g.vn(this.element,a);g.O(this.context.G.getRootNode(),g.fT.IV_DRAWER_ENABLED,a);A3(this.G)};
g.k.destroy=function(){this.G.Ut(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.hu(this.Y);g.Ot(this.va);this.La&&this.La.dispose();this.C&&this.C.dispose();d4.prototype.destroy.call(this)};
g.k.AS=function(){if(this.u){t4(this.context.logger,n4(this).tracking.close);var a=g.ix();a&&this.J&&g.Ex(a,this.J);h4(this)}};
g.k.NS=function(){g.O(this.B,"iv-drawer-scrolled",0<this.j.scrollTop)};
g.k.rU=function(){var a=g.ix(),b=n4(this);b=b?b.Ke:this.Ke;a&&b&&g.Cx(a,[b])};
g.k.qU=function(){var a=g.ix(),b=n4(this);b=b?b.Ke:this.Ke;a&&b&&g.Dx(a,[b])};
g.k.fR=function(){var a=n4(this);t4(this.context.logger,a.tracking.gP);var b=g.ix();b&&a&&g.Cx(b,[a.gj,a.Ke])};
g.k.sU=function(){var a=g.ix(),b=n4(this);a&&b&&g.Dx(a,[b.gj])};
g.k.eR=function(a){var b=n4(this),c=g.ix();this.i?a?(a=this.context.logger,t4(a,b.tracking.MB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.gj&&g.Ex(c,b.gj)):(a=this.context.logger,t4(a,b.tracking.MB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ke&&g.Ex(c,b.Ke)):(a=this.context.logger,t4(a,b.tracking.MB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Ke&&g.Ex(c,this.Ke))};g.w(o4,d4);o4.prototype.Nx=function(){d4.prototype.Nx.call(this);nVa(this)};
o4.prototype.show=function(){d4.prototype.show.call(this);var a=g.ix(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Cx(a,[g.ex(b.itct)])};
o4.prototype.hide=function(){d4.prototype.hide.call(this);var a=g.ix(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Dx(a,[g.ex(b.itct)])};g.w(p4,o4);
p4.prototype.show=function(){if(!this.isActive){o4.prototype.show.call(this);if(!this.J){g.N(this.element,"iv-branding");var a=this.annotation.data;this.j=this.createElement({D:"img",Ga:["branding-img","iv-click-target"],V:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.vn(this.j,!1);var b=this.context.X.L("html5_player_branding_button_killswitch")?this.createElement({D:"div",Ga:["branding-img-container"]}):this.createElement({D:"button",Ga:["branding-img-container",
"ytp-button"]});b.appendChild(this.j);this.element.appendChild(b);var c=VUa(this.annotation);c&&(b=this.context.X.L("html5_player_branding_button_killswitch")?this.j:b,e4(this,b,c,this.annotation.id,a.session_data));rVa(this,a);this.J=!0}g.vn(this.element,!0);this.isActive=!0;this.j&&oVa(this,this.j)}};
p4.prototype.hide=function(){this.isActive&&(o4.prototype.hide.call(this),g.vn(this.element,!1),this.isActive=!1)};
p4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);o4.prototype.destroy.call(this)};g.w(q4,o4);g.k=q4.prototype;g.k.show=function(){this.isActive||(o4.prototype.show.call(this),this.W||(tVa(this),this.W=!0),g.vn(this.element,!0),g.zi(function(){g.Eq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,s4(this),uVa(this),vVa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.TC=function(a,b,c,d,e,f){return this.isCollapsed?!1:o4.prototype.TC.call(this,a,b,c,d,e,f)};
g.k.CT=function(a){this.N=!0;r4(this,500,a)};
g.k.BT=function(){this.N=!1;wVa(this)};
g.k.wT=function(a){a.stopPropagation();this.hide()};
g.k.xT=function(a){a.stopPropagation();s4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();o4.prototype.destroy.call(this)};g.w(u4,g.qM);g.k=u4.prototype;g.k.sf=function(a,b){if(!KVa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.W1(b))&&v4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(eVa(this.i,b),A3(this.player)),!0}return null};
g.k.getOptions=function(){return KVa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Uq=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.tM||a.W.get(b.videoId)||g.LF(b)||g.MF(b)?!0:!1};
g.k.QA=function(){if(this.u){var a=this.player.bb().getVideoContentRect(!0);g.tn(this.u.element,a.width,a.height);g.on(this.u.element,a.left,a.top)}if(this.i){var b=this.player.Cj();a=this.i;b=b.width;g.O(a.B,"iv-drawer-small",426>=b);g.O(a.B,"iv-drawer-big",1280<=b)}};
g.k.gR=function(a){zVa(this,a.state);g.U(a.state,2)&&(this.Fh()&&this.Ik()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ut(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Rs(h)&&h.responseXML?h.responseXML:null)&&(v4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.qM.prototype.load.call(this);zVa(this,this.player.zb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.ot()&&(a=CVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().W.get(d);f&&DVa(e,f);f=f&&(f.ez||f.Cv);if(!c.wp||f)c.Qa?AVa(this,c.Qa,e):(this.Cl=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Cl));
g.cM(this.player,this.u.element,4);this.QA();(f=g.LF(c))&&IVa(this,f);(f=g.MF(c))&&f.featuredChannel&&JVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Qa&&(this.Cl&&(this.player.removeEventListener("videodatachange",this.Cl),this.Cl=null),AVa(this,b.Qa,a))};
g.k.unload=function(){this.player.df("annotations_module");for(var a=g.q(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.i&&(this.i.destroy(),this.i=null,A3(this.player));this.N=!1;this.C&&(this.C.abort(),this.C=null);this.I={};this.j.hide();g.qM.prototype.unload.call(this);this.u.detach();this.Cl&&(this.player.removeEventListener("videodatachange",this.Cl),this.Cl=null)};
g.k.XN=function(a){a===this.player.getVideoData().videoId&&(this.loaded?EVa(this):this.load())};
g.k.Fh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Ik=function(){this.Fh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Fh();this.i&&(a?c?g4(this.i,c,b):g4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):h4(this.i))};
g.k.Ut=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.T().W.unsubscribe("vast_info_card_add",this.XN,this);g.Eq(this.player.getRootNode(),g.fT.IV_DRAWER_OPEN);for(var a=this.W,b=0,c=a.length;b<c;b++)g.au.ri(a[b]);this.W.length=0;g.qM.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.pM("annotations_module",u4);g.pM("creatorendscreen",M3);})(_yt_player);
